# Generated by Django 4.1.5 on 2023-01-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('styles', models.TextField()),
                ('size', models.CharField(max_length=20)),
                ('imageURL', models.TextField()),
                ('image2URL', models.TextField()),
                ('image3URL', models.TextField()),
            ],
        ),
    ]
